# Generated by Django 4.2.16 on 2024-12-14 11:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opulaadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpm_organization', models.CharField(max_length=50)),
                ('tpm_pan_no', models.CharField(help_text='Enter a valid PAN number (format: AAAAA9999A)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number (format: AAAAA9999A)', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('tpm_gst_no', models.CharField(help_text='Enter a valid GST number (format, 27AACCG1234F1Z5)', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number (format: XXAAAAA1234A1Z1)', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[0-9]{1}[A-Z]{1}[0-9]{1}$')])),
                ('tpm_created_at', models.DateTimeField(auto_now_add=True)),
                ('tpm_upadated_at', models.DateTimeField(auto_now=True)),
                ('tpm_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opulaadmin.industrymastermodel')),
                ('tpm_tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantEmpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opulaadmin.tenantmodel')),
                ('tem_tenant_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
