# Generated by Django 4.2.16 on 2024-12-23 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opulaadmin', '0002_contactusmodel_alter_authenticationmodel_last_login_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opulatenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantempmodel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tenantprofilemodel',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='tenantempmodel',
            name='tem_tenant',
            field=models.ForeignKey(db_column='tem_tenant', on_delete=django.db.models.deletion.CASCADE, to='opulaadmin.tenantmodel'),
        ),
        migrations.AlterField(
            model_name='tenantempmodel',
            name='tem_tenant_emp',
            field=models.ForeignKey(db_column='tem_tenant_emp', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenantprofilemodel',
            name='tpm_industry',
            field=models.ForeignKey(db_column='tpm_industry', on_delete=django.db.models.deletion.CASCADE, to='opulaadmin.industrymastermodel'),
        ),
        migrations.AlterField(
            model_name='tenantprofilemodel',
            name='tpm_organization',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='tenantprofilemodel',
            name='tpm_tenant_user',
            field=models.ForeignKey(db_column='tpm_tenant_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='tenantempmodel',
            table='employee_management"."tenantemployeemanagement',
        ),
        migrations.AlterModelTable(
            name='tenantprofilemodel',
            table='management"."tenantprofilemanagement',
        ),
    ]
