# Generated by Django 4.2.16 on 2025-01-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opulaadmin', '0002_contactusmodel_alter_authenticationmodel_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringmodel',
            name='hm_job_skills',
            field=models.ManyToManyField(related_name='hiring_jobs', to='opulaadmin.jobskillmodel'),
        ),
    ]
