# Generated by Django 4.2.16 on 2025-01-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opulaadmin', '0003_hiringmodel_hm_job_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiringmodel',
            old_name='hm_last_submission_data',
            new_name='hm_last_submission_date',
        ),
    ]
