name: Copy Files to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: "15.206.166.15"            # Replace with your server IP
      SERVER_USER: "admin"                  # Replace with your server username
      SERVER_PASSWORD: "3ts7RCGj~5" # Replace with your actual password
      TARGET_PATH: "/var/www/html/"         # Replace with your desired target path

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy All Files from Main Repo to Remote Server
        run: |
          sudo sshpass -p "$SERVER_PASSWORD" scp -r -o StrictHostKeyChecking=no inance-html spering-html $SERVER_USER@$SERVER_IP:$TARGET_PATH
          sudo sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sudo systemctl restart nginx"
