name: SSH and Copy File

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
      
      - name: Copy File to Remote Server
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no Testing.txt $SERVER_USER@$SERVER_IP:/tmp/
      
      - name: Move File to Root Directory on Remote Server
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          sudo mv /tmp/Testing.txt /
          EOF
      
      - name: Clean Up
        run: |
          rm -f private_key.pem
