name: Deploy Remotely

on:
  push:
    branches: [ main ]
 
jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Set up Node.js 20.x to build your app
    - name: Use Node.js 20.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    
    - run: npm install
    - run: CI=false npm run build

    # Install sshpass for password-based SSH authentication
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    # Deploy to the remote server using SSH with password
    - name: Transfer Build Folder on EC2 Instance
      run: |
        sshpass -p ${{ secrets.DEPLOY_PASSWORD }} scp -r build/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_TARGET }}
      env:
        DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_TARGET: ${{ secrets.DEPLOY_TARGET }}
