name: Copy Files to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Set Target Path
        run: echo "TARGET_PATH=/var/www/html/" >> $GITHUB_ENV

      - name: Copy Files to Remote Server
        run: |
          sshpass -p "$SERVER_PASSWORD" scp -r -o StrictHostKeyChecking=no spering-html inance-html "$SERVER_USER@$SERVER_IP:$TARGET_PATH"
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "sudo systemctl restart nginx"
