name: Copy File to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy Testing.txt to Remote Server
        run: |
          sudo sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no spering_html/* $SERVER_USER@$SERVER_IP:/var/www/html/spering
          sudo systemctl restart nginx
          
