name: Copy Files to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      TARGET_PATH: "/var/www/html/"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy Files to Remote Servera
        run: |
          sshpass -p "$SERVER_PASSWORD" scp -r -o StrictHostKeyChecking=no ./OpulaBackend "$SERVER_USER@$SERVER_IP:/tmp/temp_upload"
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "sudo mv /tmp/temp_upload/* $TARGET_PATH && sudo systemctl restart nginx"
